# Generated by Django 2.1.5 on 2019-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
